Repository James-d-Harris/QuickChange, pull requests merged in 2024-11, with the labels that each got.

#97 Update AutomatedTesting.cs
  Scripts/Editor/AutomatedTesting.cs
Labels: bug, enhancement, code

#96 Update Student.cs
  Scripts/Game/Student.cs
Labels: bug, enhancement, code

#99 Created design.md
  Project Documentation/README.md
  Project Documentation/README.md.meta
  Project Documentation/analysis.md
  Project Documentation/analysis.md.meta
  Project Documentation/code_of_conduct.md
  Project Documentation/code_of_conduct.md.meta
  Project Documentation/contributing.md
  Project Documentation/contributing.md.meta
  Project Documentation/design.md
  Project Documentation/implementations.md
  Project Documentation/implementations.md.meta
  Project Documentation/inception.md
  Project Documentation/inception.md.meta
  Project Documentation/license.md
  Project Documentation/license.md.meta
  Project Documentation/requirements.md
  Project Documentation/requirements.md.meta
  images/D5UMLClassDiagram.png
Labels: documentation, D5 design

#100 Automated testing
  Scripts/Editor/AutomatedTesting.cs
  Scripts/Game/DifficultyClass.cs
Labels: enhancement, code

#105 Update design.md
  Project Documentation/design.md
Labels: documentation, D5 design

#108 Update design.md
  Project Documentation/design.md
  images/D5UMLClassDiagram.png
Labels: documentation, enhancement, feedback, D5 design

#110 Update image path
  Project Documentation/analysis.md
  Project Documentation/design.md
  Project Documentation/implementations.md
  Project Documentation/requirements.md
Labels: enhancement, Preperation, feedback

#113 Create implementations-2.md
  Project Documentation/implementations-2.md
Labels: documentation, D6 Implementation

#116 Created unity-issue branch
  Project Documentation.meta
  Project Documentation/design.md.meta
  Scripts/Editor/AutomatedTesting.cs
  Scripts/Game/Student.cs
  Scripts/Game/coinSumDisplayClass.cs
  images/D5UMLClassDiagram.png.meta
  images/D5UMLObserver.png.meta
  images/use case 5 play level.drawio.png.meta
Labels: bug, Preperation, code

#133 D6 work
  Project Documentation/implementations-2.md
  Scripts/Editor/AcceptanceTesting.cs
  Scripts/Editor/UnitTesting.cs
  Scripts/Editor/UnitTesting.cs.meta
  images/unityCustomerAssetScreenshot.png
  images/unityTeacherView.png
  images/unityregisterUIscreenshot.png
Labels: documentation, enhancement, code, D6 Implementation

#126 Register UI
  Blueprints/Primary.prefab
  Scenes/MainScene.unity
  Scripts/Game/registerClass.cs
Labels: code, D6 Implementation

#134 Last minute unity errors
  Scripts/Editor/AcceptanceTesting.cs
  Scripts/Editor/AcceptanceTesting.cs.meta
  Scripts/Game/registerClass.cs
  images/unityCustomerAssetScreenshot.png.meta
  images/unityTeacherView.png.meta
  images/unityregisterUIscreenshot.png.meta
Labels: bug, code, D6 Implementation

#135 Updated implementations-2.md
  Project Documentation/implementations-2.md
Labels: documentation, enhancement, D6 Implementation
