Repository James-d-Harris/QuickChange, pull requests merged in 2024-10, with the labels that each got.

#34 Create analysis.md
  analysis.md
Labels: documentation, D3 Analysis

#40 Updated D2
  images/UseCaseInterfaceSketchTate.drawio.png
  requirements.md
Labels: documentation, enhancement, Deliverable 2

#43 Add files via upload
  images/UseCaseSean.JPG
Labels: documentation, Deliverable 2

#45 Update requirements.md
  requirements.md
Labels: documentation, enhancement, Deliverable 2

#46 Update requirements.md
  requirements.md
Labels: documentation, enhancement, Deliverable 2

#47 Updated analysis.md
  analysis.md
  images/UMLDiagramD3.drawio.png
Labels: documentation, enhancement, D3 Analysis

#50 Updated analysis.md
  analysis.md
  images/UMLDiagramD3UPDATED.png
Labels: documentation, enhancement, D3 Analysis

#58 Created currency and register class, added to Scripts
  .gitignore
  Plugins/DnsClient.dll
  Plugins/Microsoft.Extensions.Logging.Abstractions.dll
  Plugins/Microsoft.Win32.Registry.dll
  Plugins/MongoDB/MongoDB.Bson.dll
  Plugins/MongoDB/MongoDB.Driver.dll
  Plugins/SharpCompress.dll
  Plugins/Snappier.dll
  Plugins/System.Buffers.dll
  Plugins/System.Memory.dll
  Plugins/System.Numerics.Vectors.dll
  Plugins/System.Runtime.CompilerServices.Unsafe.dll
  Plugins/System.Security.AccessControl.dll
  Plugins/System.Security.Principal.Windows.dll
  Plugins/System.Text.Encoding.CodePages.dll
  Plugins/ZstdSharp.dll
  Scenes/LoginScene.unity
  Scenes/SampleScene.unity
  Scenes/SampleScene.unity.meta
  Scripts/Database/MongoDBManager.cs
  Scripts/Game/Student.cs
  Scripts/Game/Teacher.cs
  Scripts/Game/coinClass.cs
  Scripts/Game/registerClassUpdated.cs
  Scripts/LoginUI.cs
  TextMesh Pro/Documentation/TextMesh Pro User Guide 2016.pdf
  TextMesh Pro/Fonts/LiberationSans - OFL.txt
  TextMesh Pro/Fonts/LiberationSans.ttf
  TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Drop Shadow.mat
  TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Outline.mat
  TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  TextMesh Pro/Resources/LineBreaking Following Characters.txt
  TextMesh Pro/Resources/LineBreaking Leading Characters.txt
  TextMesh Pro/Resources/Sprite Assets/EmojiOne.asset
  TextMesh Pro/Resources/Style Sheets/Default Style Sheet.asset
  TextMesh Pro/Resources/TMP Settings.asset
  TextMesh Pro/Shaders/TMP_Bitmap-Custom-Atlas.shader
  TextMesh Pro/Shaders/TMP_Bitmap-Mobile.shader
  TextMesh Pro/Shaders/TMP_Bitmap.shader
  TextMesh Pro/Shaders/TMP_SDF Overlay.shader
  TextMesh Pro/Shaders/TMP_SDF SSD.shader
  TextMesh Pro/Shaders/TMP_SDF-Mobile Masking.shader
  TextMesh Pro/Shaders/TMP_SDF-Mobile Overlay.shader
  TextMesh Pro/Shaders/TMP_SDF-Mobile SSD.shader
  TextMesh Pro/Shaders/TMP_SDF-Mobile.shader
  TextMesh Pro/Shaders/TMP_SDF-Surface-Mobile.shader
  TextMesh Pro/Shaders/TMP_SDF-Surface.shader
  TextMesh Pro/Shaders/TMP_SDF.shader
  TextMesh Pro/Shaders/TMP_Sprite.shader
  TextMesh Pro/Shaders/TMPro.cginc
  TextMesh Pro/Shaders/TMPro_Mobile.cginc
  TextMesh Pro/Shaders/TMPro_Properties.cginc
  TextMesh Pro/Shaders/TMPro_Surface.cginc
  TextMesh Pro/Sprites/EmojiOne Attribution.txt
  TextMesh Pro/Sprites/EmojiOne.json
  TextMesh Pro/Sprites/EmojiOne.png
Labels: D4 Implementation, code

#63 Updated coin class and register class
  Scripts/Game/coinClass.cs
  Scripts/Game/registerClassUpdated.cs
Labels: enhancement, D4 Implementation, code

#65 Updated coin sum display class code
  Scripts/Game/coinSumDisplayClass
Labels: enhancement, D4 Implementation, code

#66 Changed file type for coin sum display class
  Scripts/Game/coinSumDisplayClass.cs
Labels: documentation, enhancement, D4 Implementation, code

#70 Itzpongobranch
  README.md.meta
  Scripts/Game/CustomerClass.cs
Labels: D4 Implementation, code

#71 Itzpongobranch
  Scripts/Game/ItemClass.cs
Labels: D4 Implementation, code
